version: '3.1'

services:
  mongo:
    image: mongo:6.0.3
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

#  kitezh-book-library:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#      - "8080:8080"